[build]
  # 构建命令
  command = "npm run build"
  
  # 发布目录
  publish = "dist"

[build.environment]
  # Node.js 版本
  NODE_VERSION = "18"

# 重定向规则（如果需要）
[[redirects]]
  from = "/content/*"
  to = "/content/:splat"
  status = 200

[[redirects]]
  from = "/ui-showcase"
  to = "/ui-showcase/"
  status = 200

# 404 页面处理
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

# 静态资源缓存
[[headers]]
  for = "/_astro/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# API 路由处理
[[redirects]]
  from = "/api/*"
  to = "/api/:splat"
  status = 200
